[project]
name = "uptime kuma loader"
version = "0.0.1"
authors = [
    { name="Edgd1er", email="edgd1er@hotmail.com" },
]
description = "Read configuration from file, import it through uptime-kuma-s api. delete non configured items if required."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = {text = "GNU General Public License v3.0" }
#license = {file = ["LICEN[CS]E"] }
#license = "GNU General Public License v3.0"
#license-files = ["LICEN[CS]E"]

dependencies = [
    "uptime-kuma-api",
    "tomli",
    "influxdb-client",
    "mysql-connector-python",
    "http-plot-server"
]

[project.optional-dependencies]
dev = ["black", "isort"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
description=""

[project.urls]
Homepage = "https://github.com/edgd1er/uptime-kuma-loader"
Issues = "https://github.com/edgd1er/uptime-kuma-loader/issues"


[tool.setuptools.packages.find]
where = ["."]

#[project.scripts]
#linky = "linky.__main__:main"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
